### PR TITLE
Create runtime.txt

### PR DESCRIPTION
**Pull request by capJavert**
Heroku auto builds this in python3.x evnironment. 
In python3 app fails on start with:

2017-10-15T15:15:39.481094+00:00 app[web.1]:   File "manage.py", line 4, in <module>
2017-10-15T15:15:39.481198+00:00 app[web.1]:     from app import app, db, setup_all
2017-10-15T15:15:39.481214+00:00 app[web.1]:   File "/app/app.py", line 51
2017-10-15T15:15:39.481215+00:00 app[web.1]:     except Exception, e:
2017-10-15T15:15:39.481234+00:00 app[web.1]:                     ^
2017-10-15T15:15:39.481247+00:00 app[web.1]: SyntaxError: invalid syntax

With this config file app is correctly built and starts.

**EDIT: If you are adding this file on existing project you need to add the file to git and push new commit with a file to heroku.**

### CODE REVIEW

**Comment by calvinti12** [comment]
Having the same issue

**Comment by utkarshkvs1** [comment]
change all the `except Exception, e :`   to   `except Exception as e :` 
I think the problem is due to python version , I got the same problem .
@mayukh18 can you please tell us which version of python are you using ?

**Comment by capJavert** [comment]
@utkarshkvs1 He is using python 2.x, you can see that from the syntax. For some time now Heroku builds python apps in python 3.x. This is why I added config file so Heroku can recognize that this app needs to be built in python 2.x environment. :)
@calvinti12 just add this file to your cloned directory and it will work

**Comment by utkarshkvs1** [comment]
thanks @capJavert for help , can you tell how to install requirements for python2 while having python3 as default.
the command `pip install -r requirements.txt` install the modules for default version of python .

**Comment by utkarshkvs1** [comment]
getting the same issue even after adding runtime.txt 

`2017-10-20T15:17:54.661934+00:00 heroku[web.1]: Starting process with command `python manage.py runserver --host 0.0.0.0 --port ${PORT}`
2017-10-20T15:17:58.601697+00:00 heroku[web.1]: Process exited with status 1
2017-10-20T15:17:58.439795+00:00 app[web.1]: Traceback (most recent call last):
2017-10-20T15:17:58.439821+00:00 app[web.1]:   File "manage.py", line 4, in <module>
2017-10-20T15:17:58.440018+00:00 app[web.1]:     from app import app, db, setup_all
2017-10-20T15:17:58.440040+00:00 app[web.1]:   File "/app/app.py", line 51
2017-10-20T15:17:58.440059+00:00 app[web.1]:     except Exception, e:
2017-10-20T15:17:58.440086+00:00 app[web.1]:                     ^'

**Comment by capJavert** [comment]
@utkarshkvs1 did you added runtime.txt file to git and commited, pushed to origin/heroku?

**Comment by utkarshkvs1** [comment]
@capJavert  
I've commited the changes to my repository 
but now It's showing 

Counting objects: 7, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (7/7), 756 bytes | 0 bytes/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python app detected
remote:  !     The latest version of Python 3 is python-3.6.2 (you are using +python-2.7.14, which is unsupported).
remote:  !     We recommend upgrading by specifying the latest version (python-3.6.2).
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> Found python-3.6.2, removing
remote: -----> Installing +python-2.7.14
**remote:  !     Requested runtime (+python-2.7.14) is not available for this stack (heroku-16).**
remote:  !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to blindchat9211.
remote: 
To https://git.heroku.com/blindchat9211.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/blindchat9211.git'

Please help

**Comment by mayukh18** [comment]
Thanks @capJavert for pointing this out. It indeed seems heroku builds have changed. However, as @utkarshkvs1 said the `runtime.txt` did not solve the problem. Yes I pushed it after commit. Are we missing something here?

**Comment by mayukh18** [comment]
@utkarshkvs1 can you lead us to how you got this?

**Comment by utkarshkvs1** [comment]
replying to @mayukh18 
I got this when I tried to deploy the app to heroku using `git push heroku master` after commiting the changes suggested by @capJavert

**Comment by mayukh18** [comment]
Seems to be some anomaly @utkarshkvs1 because it's working fine.

**Pull request merged**
