### PR TITLE
Modify alias generation method

### PR DESCRIPTION
**Pull request by gkeller2**
Now, aliases consist of a prefix + noun pair, or a noun + suffix
pair.

Issue #1

### CODE REVIEW

**Comment by gkeller2** [comment]
Sample output of the new alias generator:

>>> import alias                  
>>> alias.generate_alias("male")  
'StickyMonkey'
>>> alias.generate_alias("male")
'CheetahTheSecond'
>>> alias.generate_alias("female")
'DaringAmazon'
>>> alias.generate_alias("female")
'WonderWomanOfTheWastelands'

**Comment by mayukh18** [comment]
Nice one. @gkeller2 can you just remove or modify the suffixes to keep the suffixes limited to 10-12 letters max. Otherwise, the aliases will be longer than preferable on a small mobile screen.
If the number of suffixes comes down due to the limitation, just keep the random chance (probability) of prefix/suffix as 1:2 rather than 1:1 for now till we get more suffixes.

**Comment by gkeller2** [comment]
@mayukh18 : suffixes are now all at or below 12-char in length. And added several more to make the list larger.

**Comment by mayukh18** [comment]
Looks cool @gkeller2 . Great work!

**Pull request merged**
